defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image : circleci/node:10.14
  environment:
    REVIEWDOG_VERSION: 0.9.11

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - persist_to_workspace:
        root: .
        paths:
          - .

  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - run:
        command: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
        name: install reviewdog
    - run:
        command: npx textlint *.md
        name: textlint
    # - run:
    #     command: npx textlint -f checkstyle *.md | ./reviewdog -f checkstyle -diff="git diff master" -reporter=github-pr-review
    #     name: reviewdog
    #     when: on_fail

workflows:
  version: 2
  test:
    jobs:
      - setup
      - test:
          requires:
            - setup
